### ISSUE TITLE
How can i change the BirdsCount variable value ?

### ISSUE THREAD

**Issue by Csharper1972** [black-square/BirdFlock#3]
In the Main.cs script there is a line:

`public float BirdsCount = 10;`

I tried to change it to 10 to 100 to 1000 to 1 but it didn't change the number of birds when running the game.

I want to be able to change the number of birds in two cases one when the game is running and then in the Inspector on the Main.cs script attched to the Main Camera if i type change the value to 1 there will be 1 bird if i change to 60 there will be 60 birds.

The second case is when the game not running when i'm in the editor and change the value in the Inspector and then running the game.

What i did so far and i guess i'm wrong is added a public variable to the top of the Main.cs:

`public int _birdscount;`

Then in the Update function i added this:

`bool isepressed = false;
  void Update()
  {
        if (Input.GetKeyDown ("space")) 
            OnSettingsClick ();

```
    if (Input.GetKeyDown("e"))
    {
        isepressed = true;
        BoidSettingsEx eee;
        eee = settings.boidSettings[settings.instancePointNum];
        eee.BirdsCount = _birdscount;
        SaveSettings `();
    }

//We call it here to be sure that click on button desn't lead to camera target changing
if( !guiTools.MouseOverGUI && Input.GetMouseButtonDown(0) )
  cameraControl.CheckForNewTarget( Input.mousePosition );

guiTools.ManualUpdate();
```

  }`

And in the SaveSettings i did:

`void SaveSettings()
    {
        if (Application.isEditor) {
            using (var str = new FileStream (SettingsFilePath, FileMode.Create))
                serializer.Serialize (str, settings);
        }
        if (isepressed == true) {
            using (var str = new FileStream (SettingsFilePath, FileMode.Create))
                serializer.Serialize (str, settings);
            isepressed = false;
        }
    }`

So when i click the e button it should change the value and update the Settings.xml file on the hard disk. 

So it does changing the value in the Settings.xml file in the first part:

<BirdsCount>6</BirdsCount>

But in the other two places in the file where there is the line:

<BirdsCount>10</BirdsCount> The value not change.

Thank you for the help

**Comment by black-square** [comment]
Sorry for delayed response.
You can change the **Number of Birds** from Settings. You don't need to modify the code:
<img width="527" alt="screen shot 2016-10-03 at 00 10 34" src="https://cloud.githubusercontent.com/assets/3925065/19026571/e7c9e7de-88fd-11e6-9657-25acc9911f1f.png">
Don't forget to press "Restart" after that

**Comment by Csharper1972** [comment]
Great Thank you.
