### ISSUE TITLE
How can i create two new way points on my own terrain and scene ?

### ISSUE THREAD

**Issue by Csharper1972** [black-square/BirdFlock#4]
I can use your scenes the Main and it will work fine.
But i'm trying to use the whole package on my own scene and i want to make simple two way points so the birds will fly between them. So i added two Spheres to my scene and added to them the Trace script.
And added to the Main Camera the scripts camera control and main and drawer but i can't see the birds.

Even there are 100 birds i can't see them. Double click on any of the birds when the game is tunning not moving the camera to the clicked bird. But i can see the objects the birds moving i see in the Inspector i see the X  Y  Z change.

So i can't figure out what i did wrong. 
Could you show me a sample how to make it work on a terrain with only two spheres as way points ?

Or maybe to take a look on my project ?

Thank you.

**Comment by black-square** [comment]
Take a look at `Slalom` GameObject in the main scene. It contains `instancePointSlalom` and many `WayPointNNN` GameObjects as children. 
`instancePointSlalom` has `Trace` script attached and `WayPointNNN` has `WayPoint`.
You need to reproduce the same structure in your own scene and set all the properties of `Trace` and `WayPoint` respectively.
If it didn't help try a reverse approach. You can start from the main scene, delete everything you don't need and modify the rest of it for your own needs.
BTW, what kinds of project you want to implement by using this code?
